name: House Prediction CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Step 1: Seedha home directory mein jayein
            cd ~
            # Step 2: GitHub se naya code lein
            git pull origin main
            # Step 3: Docker container ko refresh karein
            sudo docker build -t house-app .
            sudo docker stop house-container || true
            sudo docker rm house-container || true
            sudo docker run -d -p 8501:8501 --name house-container house-app