name: House Prediction CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/House_Prediction

            git pull origin main

            sudo docker build -t house-app .

            sudo docker stop house-container || true
            sudo docker rm house-container || true

            sudo docker run -d \
              -p 8501:8501 \
              --name house-container \
              house-app
