name: House Prediction CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Go to project directory
            cd ~/House_Prediction

            # Pull latest code from GitHub
            git reset --hard
            git clean -fd
            git pull origin main

            # Rebuild Docker image
            sudo docker build -t house-app .

            # Remove old container if exists (force stop)
            sudo docker rm -f house-container || true

            # Kill any process using port 8501 (safety net)
            sudo fuser -k 8501/tcp || true

            # Run fresh container
            sudo docker run -d \
              -p 8501:8501 \
              --name house-container \
              house-app

            # Optional: show running containers for logs
            sudo docker ps
