name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Update
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~
            git pull origin main
            # Docker commands to refresh your app
            docker build -t house-prediction-app .
            docker stop house-app || true
            docker rm house-app || true
            docker run -d -p 8501:8501 --name house-app house-prediction-app